server:
  port: 80
  tomcat:
    uri-encoding: UTF-8




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Poll
    username: root
    password: tang753738732
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
#日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出
  level:
    root: info
  path: E:/test/logback.log
